#!/usr/bin/env ruby

require "ticket_viewer"

begin
  TicketViewer::CLI.start
rescue Timeout::Error
  puts "Request timed out. Try again or check http://www.zendesk.com/support/system-status"
rescue TicketViewer::Error => ex
  puts ex.message
end
